'use client'
import React, { useState, useEffect } from 'react';
import { Inter } from "next/font/google";
import "./globals.css";
import { Dropdown } from 'flowbite';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const [loginState, setLoginState] = useState(false);

  const handleSubmit = (e) => {
    e.preventDefault();
    setLoginState(true)
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex fixed top-0 left-0 w-full z-10 bg-white shadow-md p-4">
          <div className="flex items-center">
            <img className="w-10 mr-2" src="img/logo-small.png" />
            <p className="text-gray-700">PERGILOKA</p>
          </div>
          <div className="ml-auto">
            {loginState == false ?
              <>
                <button data-modal-target="login-modal" data-modal-toggle="login-modal" type="button" class="inline-flex items-center justify-center bg-indigo-600 text-white py-2 px-7 rounded-md mr-2 hover:bg-indigo-700 active:shadow-inner">
                  Masuk
                </button>
                <button data-modal-target="daftar-modal" data-modal-toggle="daftar-modal" type="button" class="inline-fflex items-center justify-center border border-indigo-600 bg-white text-indigo-600 py-2 px-7 rounded-md hover:bg-gray-100 active:shadow-inner">
                  Daftar
                </button>
              </>
              :
              <>
                <button id="userDropdownButton" data-dropdown-toggle="userDropdown" class="cursor-pointer inline-flex items-center justify-center bg-indigo-600 text-white py-2 px-5 rounded-md mr-2 hover:bg-indigo-700 active:shadow-inner" type="button">
                  Fulan bin Fulan
                  <svg class="w-2.5 h-2.5 ms-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4" />
                  </svg>
                </button>
                <div id="userDropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44">
                  <ul class="py-2 text-sm text-gray-700" aria-labelledby="userDropdownButton">
                    <li>
                      <a href="/pesanan" class="block px-4 py-2 hover:bg-gray-100">Pesanan Saya</a>
                    </li>
                  </ul>
                  <div class="py-2">
                    <a href="#" class="block text-gray-700 text-sm px-4 py-2 hover:bg-gray-100">Keluar</a>
                  </div>
                </div>
              </>
            }

          </div>
        </div>
        {children}

        <div id="login-modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
          <div class="relative p-4 w-full max-w-2xl max-h-full">
            <form onSubmit={handleSubmit}>
              <div class="relative bg-white rounded-lg shadow">
                <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t">
                  <h3 class="text-xl font-semibold text-gray-900">
                    Masuk
                  </h3>
                  <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center" data-modal-hide="login-modal">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                    </svg>
                    <span class="sr-only">Close modal</span>
                  </button>
                </div>
                <div class="p-4 md:p-5 space-y-4">
                  <div className="grid grid-cols-12 gap-4">
                    <div className="col-span-12">
                      <label className="inline-block mb-2 text-md text-gray-500 " for="email">Email <span className="text-red-500">*</span></label>
                      <input type="email" id="email" name="email" className="block w-full border border-gray-200 appearance-none rounded-md py-2 px-2.5 focus:ring-2 focus:ring-indigo-400" required />
                    </div>
                    <div className="col-span-12">
                      <label className="inline-block mb-2 text-md text-gray-500 " for="password1">Kata Sandi <span className="text-red-500">*</span></label>
                      <input type="password" id="password1" name="password1" className="block w-full border border-gray-200 appearance-none rounded-md py-2 px-2.5 focus:ring-2 focus:ring-indigo-400" required />
                    </div>
                  </div>
                </div>
                <div class="flex items-center justify-center p-4 md:p-5 border-t border-gray-200 rounded-b">
                  <button data-modal-hide="login-modal" type="button" class="inline-flex items-center justify-center bg-gray-200 mr-2 text-black py-2 px-7 rounded-md hover:bg-gray-300 active:shadow-inner">Batal</button>
                  <button data-modal-hide="login-modal" type="submit" class="inline-flex items-center justify-center bg-indigo-600 text-white py-2 px-7 rounded-md mr-2 hover:bg-indigo-700 active:shadow-inner">Masuk</button>
                </div>
              </div>
            </form>
          </div>
        </div>

        <div id="daftar-modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
          <div class="relative p-4 w-full max-w-2xl max-h-full">
            <form>
              <div class="relative bg-white rounded-lg shadow">
                <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t">
                  <h3 class="text-xl font-semibold text-gray-900">
                    Daftar
                  </h3>
                  <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center" data-modal-hide="daftar-modal">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                    </svg>
                    <span class="sr-only">Close modal</span>
                  </button>
                </div>
                <div class="p-4 md:p-5 space-y-4">
                  <div className="grid grid-cols-12 gap-4">
                    <div className="col-span-12">
                      <label className="inline-block mb-2 text-md text-gray-500 " for="nama-lengkap">Nama Lengkap <span className="text-red-500">*</span></label>
                      <input type="text" id="nama-lengkap" name="nama-lengkap" className="block w-full border border-gray-200 appearance-none rounded-md py-2 px-2.5 focus:ring-2 focus:ring-indigo-400" required />
                    </div>
                    <div className="col-span-12">
                      <label className="inline-block mb-2 text-md text-gray-500 " for="email">Email <span className="text-red-500">*</span></label>
                      <input type="email" id="email" name="email" className="block w-full border border-gray-200 appearance-none rounded-md py-2 px-2.5 focus:ring-2 focus:ring-indigo-400" required />
                    </div>
                    <div className="col-span-12">
                      <label className="inline-block mb-2 text-md text-gray-500 " for="password1">Kata Sandi <span className="text-red-500">*</span></label>
                      <input type="password" id="password1" name="password1" className="block w-full border border-gray-200 appearance-none rounded-md py-2 px-2.5 focus:ring-2 focus:ring-indigo-400" required />
                    </div>
                    <div className="col-span-12">
                      <label className="inline-block mb-2 text-md text-gray-500 " for="password2">Masukkan Kata Sandi Kembali <span className="text-red-500">*</span></label>
                      <input type="password" id="password2" name="password2" className="block w-full border border-gray-200 appearance-none rounded-md py-2 px-2.5 focus:ring-2 focus:ring-indigo-400" required />
                    </div>
                  </div>
                </div>
                <div class="flex items-center justify-center p-4 md:p-5 border-t border-gray-200 rounded-b">
                  <button data-modal-hide="daftar-modal" type="button" class="inline-flex items-center justify-center bg-gray-200 mr-2 text-black py-2 px-7 rounded-md hover:bg-gray-300 active:shadow-inner">Batal</button>
                  <button data-modal-hide="daftar-modal" type="submit" class="inline-flex items-center justify-center bg-indigo-600 text-white py-2 px-7 rounded-md mr-2 hover:bg-indigo-700 active:shadow-inner">Daftar</button>
                </div>
              </div>
            </form>
          </div>
        </div>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
        <script src="js/datepicker.js"></script>

      </body>
    </html>
  );
}